variable "aws_security_group_workspaces_qq" {}
variable "subnets_trusted" {}
variable "aws_directory_service_directory" {}
variable "dev_users" {}
variable "dev_image_id" {}
variable "guest_users" {}
variable "guest_image_id" {}
variable "vpc_name" {}
variable "app_image_id" {}
variable "app_users" {}
